const lastChecked = "September 5, 2023";
const newInfo = [
    {
        country: {"name":"Afghanistan","url":"https://en.wikipedia.org/wiki/Afghanistan"}, 
        leader: {"title":"Supreme Leader","pos":"supreme leader","name":"Hibatullah Akhundzada","url":"https://en.wikipedia.org/wiki/Hibatullah_Akhundzada","imgUrl":"https://upload.wikimedia.org/wikipedia/en/thumb/3/3a/Hibatullah_Akhundzada.jpg/500px-Hibatullah_Akhundzada.jpg"}, 
        flag: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_the_Taliban.svg/500px-Flag_of_the_Taliban.svg.png"}, 
        symbol: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Arms_of_the_Islamic_Emirate_of_Afghanistan.svg/500px-Arms_of_the_Islamic_Emirate_of_Afghanistan.svg.png"}, 
        map: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Afghanistan_%28orthographic_projection%29.svg/500px-Afghanistan_%28orthographic_projection%29.svg.png"}, 
        capital: [{"name":"Kabul","type":"capital"}], 
        language: {"list":["Pashto","Dari"]}, 
        demonym: {"name":"Afghan"}, 
        currency: [{"demonym":"Afghan","unit":"afghani"}], 
        tld: {"name":".af"}, 
        largestCity: [{"name":"Kabul","type":"largest city"}], 
    }, 
    {
        country: {"name":"Albania","url":"https://en.wikipedia.org/wiki/Albania"}, 
        leader: {"title":"Prime Minister","pos":"prime minister","name":"Edi Rama","url":"https://en.wikipedia.org/wiki/Edi_Rama","imgUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Sre%C4%8Danje_predsednika_vlade_Roberta_Goloba_s_predsednikom_vlade_Albanije_Edijem_Ramo_%2852320651109%29_%28cropped%29.jpg/500px-Sre%C4%8Danje_predsednika_vlade_Roberta_Goloba_s_predsednikom_vlade_Albanije_Edijem_Ramo_%2852320651109%29_%28cropped%29.jpg"}, 
        flag: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Flag_of_Albania.svg/500px-Flag_of_Albania.svg.png"}, 
        symbol: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Coat_of_arms_of_Albania.svg/500px-Coat_of_arms_of_Albania.svg.png"}, 
        map: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Location_Albania_Europe.png/500px-Location_Albania_Europe.png"}, 
        capital: [{"name":"Tirana","type":"capital"}], 
        language: {"list":["Albanian"]}, 
        demonym: {"name":"Albanian"}, 
        currency: [{"demonym":"Albanian","unit":"lek"}], 
        tld: {"name":".al"}, 
        largestCity: [{"name":"Tirana","type":"largest city"}], 
    }, 
    {
        country: {"name":"Algeria","url":"https://en.wikipedia.org/wiki/Algeria"}, 
        leader: {"title":"President","pos":"president","name":"Abdelmadjid Tebboune","url":"https://en.wikipedia.org/wiki/Abdelmadjid_Tebboune","imgUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Abdelmadjid_Tebboune_%282023%29_%28cropped%29.jpg/500px-Abdelmadjid_Tebboune_%282023%29_%28cropped%29.jpg"}, 
        flag: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Flag_of_Algeria.svg/500px-Flag_of_Algeria.svg.png"}, 
        symbol: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/National_Emblem_of_Algeria.svg/500px-National_Emblem_of_Algeria.svg.png"}, 
        map: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Algeria_%28centered_orthographic_projection%29.svg/500px-Algeria_%28centered_orthographic_projection%29.svg.png"}, 
        capital: [{"name":"Algiers","type":"capital"}], 
        language: {"list":["Arabic","Tamazight"]}, 
        demonym: {"name":"Algerian"}, 
        currency: [{"demonym":"Algerian","unit":"dinar"}], 
        tld: {"name":".dz"}, 
        largestCity: [{"name":"Algiers","type":"largest city"}], 
    }, 
    {
        country: {"name":"Andorra","url":"https://en.wikipedia.org/wiki/Andorra"}, 
        leader: {"title":"Prime Minister","pos":"prime minister","name":"Xavier Espot","url":"https://en.wikipedia.org/wiki/Xavier_Espot_Zamora","imgUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Xavier_Espot_Zamora_i_Isabel_Santos_a_l%27assemblea_de_l%27OSCE_2017_%28cropped%29.jpg/500px-Xavier_Espot_Zamora_i_Isabel_Santos_a_l%27assemblea_de_l%27OSCE_2017_%28cropped%29.jpg"}, 
        flag: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Flag_of_Andorra.svg/500px-Flag_of_Andorra.svg.png"}, 
        symbol: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Coat_of_arms_of_Andorra.svg/500px-Coat_of_arms_of_Andorra.svg.png"}, 
        map: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Location_Andorra_Europe.png/500px-Location_Andorra_Europe.png"}, 
        capital: [{"name":"Andorra la Vella","type":"capital"}], 
        language: {"list":["Catalan"]}, 
        demonym: {"name":"Andorran"}, 
        currency: [{"full":"euro"}], 
        tld: {"name":".ad"}, 
        largestCity: [{"name":"Andorra la Vella","type":"largest city"}], 
    }, 
    {
        country: {"name":"Angola","url":"https://en.wikipedia.org/wiki/Angola"}, 
        leader: {"title":"President","pos":"president","name":"João Lourenço","url":"https://en.wikipedia.org/wiki/Jo%C3%A3o_Louren%C3%A7o","imgUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Jo%C3%A3o_Louren%C3%A7o_2023.jpg/500px-Jo%C3%A3o_Louren%C3%A7o_2023.jpg"}, 
        flag: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Flag_of_Angola.svg/500px-Flag_of_Angola.svg.png"}, 
        symbol: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Emblem_of_Angola.svg/500px-Emblem_of_Angola.svg.png"}, 
        map: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Angola_%28orthographic_projection%29.svg/500px-Angola_%28orthographic_projection%29.svg.png"}, 
        capital: [{"name":"Luanda","type":"capital"}], 
        language: {"list":["Portuguese"]}, 
        demonym: {"name":"Angolan"}, 
        currency: [{"demonym":"Angolan","unit":"kwanza"}], 
        tld: {"name":".ao"}, 
        largestCity: [{"name":"Luanda","type":"largest city"}], 
    }, 
    {
        country: {"name":"Antigua and Barbuda","url":"https://en.wikipedia.org/wiki/Antigua_and_Barbuda"}, 
        leader: {"title":"Prime Minister","pos":"prime minister","name":"Gaston Browne","url":"https://en.wikipedia.org/wiki/Gaston_Browne","imgUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/10_06_2022_Segunda_Sess%C3%A3o_Plen%C3%A1ria_da_IX_C%C3%BApula_das_Am%C3%A9ricas_%2852137201805%29_%28cropped%29.jpg/500px-10_06_2022_Segunda_Sess%C3%A3o_Plen%C3%A1ria_da_IX_C%C3%BApula_das_Am%C3%A9ricas_%2852137201805%29_%28cropped%29.jpg"}, 
        flag: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Flag_of_Antigua_and_Barbuda.svg/500px-Flag_of_Antigua_and_Barbuda.svg.png"}, 
        symbol: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Coat_of_arms_of_Antigua_and_Barbuda.svg/500px-Coat_of_arms_of_Antigua_and_Barbuda.svg.png"}, 
        map: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/ATG_orthographic.svg/500px-ATG_orthographic.svg.png"}, 
        capital: [{"name":"St. John's","type":"capital"}], 
        language: {"list":["English"]}, 
        demonym: {"name":"Antiguan and Barbudan"}, 
        currency: [{"full":"East Caribbean dollar"}], 
        tld: {"name":".ag"}, 
        largestCity: [{"name":"St. John's","type":"largest city"}], 
    }, 
    {
        country: {"name":"Argentina","url":"https://en.wikipedia.org/wiki/Argentina"}, 
        leader: {"title":"President","pos":"president","name":"Alberto Fernández","url":"https://en.wikipedia.org/wiki/Alberto_Fern%C3%A1ndez","imgUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Mensaje_de_fin_de_a%C3%B1o_del_Presidente_Alberto_Fern%C3%A1ndez_%28cropped%29.jpg/500px-Mensaje_de_fin_de_a%C3%B1o_del_Presidente_Alberto_Fern%C3%A1ndez_%28cropped%29.jpg"}, 
        flag: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Flag_of_Argentina.svg/500px-Flag_of_Argentina.svg.png"}, 
        symbol: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Sol_de_Mayo-Bandera_de_Argentina.svg/500px-Sol_de_Mayo-Bandera_de_Argentina.svg.png"}, 
        map: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/ARG_orthographic_%28%2Ball_claims%29.svg/500px-ARG_orthographic_%28%2Ball_claims%29.svg.png"}, 
        capital: [{"name":"Buenos Aires","type":"capital"}], 
        language: {"list":["Spanish"]}, 
        demonym: {"name":"Argentine"}, 
        currency: [{"demonym":"Argentine","unit":"peso"}], 
        tld: {"name":".ar"}, 
        largestCity: [{"name":"Buenos Aires","type":"largest city"}], 
    }, 
    {
        country: {"name":"Armenia","url":"https://en.wikipedia.org/wiki/Armenia"}, 
        leader: {"title":"Prime Minister","pos":"prime minister","name":"Nikol Pashinyan","url":"https://en.wikipedia.org/wiki/Nikol_Pashinyan","imgUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/%D0%9D%D0%B8%D0%BA%D0%BE%D0%BB_%D0%9F%D0%B0%D1%88%D0%B8%D0%BD%D1%8F%D0%BD_%2820-04-2022%29_2.jpg/500px-%D0%9D%D0%B8%D0%BA%D0%BE%D0%BB_%D0%9F%D0%B0%D1%88%D0%B8%D0%BD%D1%8F%D0%BD_%2820-04-2022%29_2.jpg"}, 
        flag: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Flag_of_Armenia.svg/500px-Flag_of_Armenia.svg.png"}, 
        symbol: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Coat_of_arms_of_Armenia.svg/500px-Coat_of_arms_of_Armenia.svg.png"}, 
        map: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Armenia_%28orthographic_projection%29.svg/500px-Armenia_%28orthographic_projection%29.svg.png"}, 
        capital: [{"name":"Yerevan","type":"capital"}], 
        language: {"list":["Armenian"]}, 
        demonym: {"name":"Armenian"}, 
        currency: [{"demonym":"Armenian","unit":"dram"}], 
        tld: {"name":".am"}, 
        largestCity: [{"name":"Yerevan","type":"largest city"}], 
    }, 
    {
        country: {"name":"Australia","url":"https://en.wikipedia.org/wiki/Australia"}, 
        leader: {"title":"Prime Minister","pos":"prime minister","name":"Anthony Albanese","url":"https://en.wikipedia.org/wiki/Anthony_Albanese","imgUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Anthony_Albanese_portrait_%28cropped%29.jpg/500px-Anthony_Albanese_portrait_%28cropped%29.jpg"}, 
        flag: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Flag_of_Australia_%28converted%29.svg/500px-Flag_of_Australia_%28converted%29.svg.png"}, 
        symbol: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Coat_of_Arms_of_Australia.svg/500px-Coat_of_Arms_of_Australia.svg.png"}, 
        map: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Australia_with_AAT_%28orthographic_projection%29.svg/500px-Australia_with_AAT_%28orthographic_projection%29.svg.png"}, 
        capital: [{"name":"Canberra","type":"capital"}], 
        largestCity: [{"name":"Sydney","type":"largest city"}], 
        language: {"list":["English"]}, 
        demonym: {"name":"Australian"}, 
        currency: [{"demonym":"Australian","unit":"dollar"}], 
        tld: {"name":".au"}, 
    }, 
    {
        country: {"name":"Austria","url":"https://en.wikipedia.org/wiki/Austria"}, 
        leader: {"title":"Chancellor","pos":"chancellor","name":"Karl Nehammer","url":"https://en.wikipedia.org/wiki/Karl_Nehammer","imgUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/2020_Karl_Nehammer_Ministerrat_am_8.1.2020_%2849351366976%29_%28cropped%29_%28cropped%29.jpg/500px-2020_Karl_Nehammer_Ministerrat_am_8.1.2020_%2849351366976%29_%28cropped%29_%28cropped%29.jpg"}, 
        flag: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Flag_of_Austria.svg/500px-Flag_of_Austria.svg.png"}, 
        symbol: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Austria_Bundesadler.svg/500px-Austria_Bundesadler.svg.png"}, 
        map: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/EU-Austria_%28orthographic_projection%29.svg/500px-EU-Austria_%28orthographic_projection%29.svg.png"}, 
        capital: [{"name":"Vienna","type":"capital"}], 
        language: {"list":["German"]}, 
        demonym: {"name":"Austrian"}, 
        currency: [{"full":"euro"}], 
        tld: {"name":".at"}, 
        largestCity: [{"name":"Vienna","type":"largest city"}], 
    }, 
    {
        country: {"name":"Azerbaijan","url":"https://en.wikipedia.org/wiki/Azerbaijan"}, 
        leader: {"title":"President","pos":"president","name":"Ilham Aliyev","url":"https://en.wikipedia.org/wiki/Ilham_Aliyev","imgUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Ilham_Aliyev_2022_%28cropped%29.jpg/500px-Ilham_Aliyev_2022_%28cropped%29.jpg"}, 
        flag: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Flag_of_Azerbaijan.svg/500px-Flag_of_Azerbaijan.svg.png"}, 
        symbol: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Emblem_of_Azerbaijan.svg/500px-Emblem_of_Azerbaijan.svg.png"}, 
        map: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Azerbaijan_with_Nagorno_Karabakh_region.svg/500px-Azerbaijan_with_Nagorno_Karabakh_region.svg.png"}, 
        capital: [{"name":"Baku","type":"capital"}], 
        language: {"list":["Azerbaijani"]}, 
        demonym: {"name":"Azerbaijani"}, 
        currency: [{"demonym":"Azerbaijani","unit":"manat"}], 
        tld: {"name":".az"}, 
        largestCity: [{"name":"Baku","type":"largest city"}], 
    }, 
    {
        country: {"name":"The Bahamas","url":"https://en.wikipedia.org/wiki/The_Bahamas"}, 
        leader: {"title":"Prime Minister","pos":"prime minister","name":"Philip Davis","url":"https://en.wikipedia.org/wiki/Philip_Davis_(Bahamian_politician)","imgUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Philip_%22Brave%22_Davis_%28profile%29.jpg/500px-Philip_%22Brave%22_Davis_%28profile%29.jpg"}, 
        flag: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Flag_of_the_Bahamas.svg/500px-Flag_of_the_Bahamas.svg.png"}, 
        symbol: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Coat_of_arms_of_the_Bahamas.svg/500px-Coat_of_arms_of_the_Bahamas.svg.png"}, 
        map: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/The_Bahamas_on_the_globe_%28Americas_centered%29.svg/500px-The_Bahamas_on_the_globe_%28Americas_centered%29.svg.png"}, 
        capital: [{"name":"Nassau","type":"capital"}], 
        language: {"list":["English"]}, 
        demonym: {"name":"Bahamian"}, 
        currency: [{"demonym":"Bahamian","unit":"dollar"}], 
        tld: {"name":".bs"}, 
        largestCity: [{"name":"Nassau","type":"largest city"}], 
    }, 
    {
        country: {"name":"Bahrain","url":"https://en.wikipedia.org/wiki/Bahrain"}, 
        leader: {"title":"King","pos":"king","name":"Hamad bin Isa Al Khalifa","url":"https://en.wikipedia.org/wiki/Hamad_bin_Isa_Al_Khalifa","imgUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/King_Hamad_bin_Isa_Al_Khalifa_of_Bahrain_Addresses_Reporters_at_the_Outset_of_a_Welcoming_Reception_for_Secretary_Kerry_in_Manama_%2826224844641%29_%28cropped%292.jpg/500px-King_Hamad_bin_Isa_Al_Khalifa_of_Bahrain_Addresses_Reporters_at_the_Outset_of_a_Welcoming_Reception_for_Secretary_Kerry_in_Manama_%2826224844641%29_%28cropped%292.jpg"}, 
        flag: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Flag_of_Bahrain.svg/500px-Flag_of_Bahrain.svg.png"}, 
        symbol: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Coat_of_Arms_of_The_Kingdom_of_Bahrain.svg/500px-Coat_of_Arms_of_The_Kingdom_of_Bahrain.svg.png"}, 
        map: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Map_of_Bahrain.svg/500px-Map_of_Bahrain.svg.png"}, 
        capital: [{"name":"Manama","type":"capital"}], 
        language: {"list":["Arabic"]}, 
        demonym: {"name":"Bahraini"}, 
        currency: [{"demonym":"Bahraini","unit":"dinar"}], 
        tld: {"name":".bh"}, 
        largestCity: [{"name":"Manama","type":"largest city"}], 
    }, 
    {
        country: {"name":"Bangladesh","url":"https://en.wikipedia.org/wiki/Bangladesh"}, 
        leader: {"title":"Prime Minister","pos":"prime minister","name":"Sheikh Hasina","url":"https://en.wikipedia.org/wiki/Sheikh_Hasina","imgUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Sheikh_Hasina_in_New_York_-_2018_%2844057292035%29_%28cropped%29.jpg/500px-Sheikh_Hasina_in_New_York_-_2018_%2844057292035%29_%28cropped%29.jpg"}, 
        flag: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Flag_of_Bangladesh.svg/500px-Flag_of_Bangladesh.svg.png"}, 
        symbol: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/National_emblem_of_Bangladesh.svg/500px-National_emblem_of_Bangladesh.svg.png"}, 
        map: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Bangladesh_%28orthographic_projection%29.svg/500px-Bangladesh_%28orthographic_projection%29.svg.png"}, 
        capital: [{"name":"Dhaka","type":"capital"}], 
        language: {"list":["Bengali"]}, 
        demonym: {"name":"Bangladeshi"}, 
        currency: [{"demonym":"Bangladeshi","unit":"taka"}], 
        tld: {"name":".bd"}, 
        largestCity: [{"name":"Dhaka","type":"largest city"}], 
    }, 
    {
        country: {"name":"Barbados","url":"https://en.wikipedia.org/wiki/Barbados"}, 
        leader: {"title":"Prime Minister","pos":"prime minister","name":"Mia Mottley","url":"https://en.wikipedia.org/wiki/Mia_Mottley","imgUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Mia_Mottley_%282021%29_%28cropped%29.jpg/500px-Mia_Mottley_%282021%29_%28cropped%29.jpg"}, 
        flag: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Flag_of_Barbados.svg/500px-Flag_of_Barbados.svg.png"}, 
        symbol: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Coat_of_arms_of_Barbados_%283%29.svg/500px-Coat_of_arms_of_Barbados_%283%29.svg.png"}, 
        map: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/BRB_orthographic.svg/500px-BRB_orthographic.svg.png"}, 
        capital: [{"name":"Bridgetown","type":"capital"}], 
        language: {"list":["English"]}, 
        demonym: {"name":"Barbadian"}, 
        currency: [{"demonym":"Barbadian","unit":"dollar"}], 
        tld: {"name":".bb"}, 
        largestCity: [{"name":"Bridgetown","type":"largest city"}], 
    }, 
    {
        country: {"name":"Belarus","url":"https://en.wikipedia.org/wiki/Belarus"}, 
        leader: {"title":"President","pos":"president","name":"Alexander Lukashenko","url":"https://en.wikipedia.org/wiki/Alexander_Lukashenko","imgUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B0%D0%BD%D0%B4%D1%80_%D0%9B%D1%83%D0%BA%D0%B0%D1%88%D0%B5%D0%BD%D0%BA%D0%BE_%2813-04-2023%29_%28cropped%29.jpg/500px-%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B0%D0%BD%D0%B4%D1%80_%D0%9B%D1%83%D0%BA%D0%B0%D1%88%D0%B5%D0%BD%D0%BA%D0%BE_%2813-04-2023%29_%28cropped%29.jpg"}, 
        flag: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Flag_of_Belarus.svg/500px-Flag_of_Belarus.svg.png"}, 
        symbol: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Coat_of_arms_of_Belarus_%282020%E2%80%93present%29.svg/500px-Coat_of_arms_of_Belarus_%282020%E2%80%93present%29.svg.png"}, 
        map: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/Europe-Belarus_%28orthographic_projection%29.svg/500px-Europe-Belarus_%28orthographic_projection%29.svg.png"}, 
        capital: [{"name":"Minsk","type":"capital"}], 
        language: {"list":["Belarusian","Russian"]}, 
        demonym: {"name":"Belarusian"}, 
        currency: [{"demonym":"Belarusian","unit":"ruble"}], 
        tld: {"name":".by"}, 
        largestCity: [{"name":"Minsk","type":"largest city"}], 
    }, 
    {
        country: {"name":"Belgium","url":"https://en.wikipedia.org/wiki/Belgium"}, 
        leader: {"title":"Prime Minister","pos":"prime minister","name":"Alexander De Croo","url":"https://en.wikipedia.org/wiki/Alexander_De_Croo","imgUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Alexander_De_Croo_%282022-04-28%29_%28cropped%29.jpg/500px-Alexander_De_Croo_%282022-04-28%29_%28cropped%29.jpg"}, 
        flag: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Flag_of_Belgium.svg/500px-Flag_of_Belgium.svg.png"}, 
        symbol: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Great_coat_of_arms_of_Belgium.svg/500px-Great_coat_of_arms_of_Belgium.svg.png"}, 
        map: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Belgium_%28orthographic_projection%29.svg/500px-Belgium_%28orthographic_projection%29.svg.png"}, 
        capital: [{"name":"Brussels","type":"capital"}], 
        largestCity: [{"name":"Antwerp","type":"largest city"}], 
        language: {"list":["Dutch","French","German"]}, 
        demonym: {"name":"Belgian"}, 
        currency: [{"full":"euro"}], 
        tld: {"name":".be"}, 
    }, 
    {
        country: {"name":"Belize","url":"https://en.wikipedia.org/wiki/Belize"}, 
        leader: {"title":"Prime Minister","pos":"prime minister","name":"Johnny Briceño","url":"https://en.wikipedia.org/wiki/Johnny_Brice%C3%B1o","imgUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Johnny_Brice%C3%B1o_%2852135383761%29_%28cropped%29.jpg/500px-Johnny_Brice%C3%B1o_%2852135383761%29_%28cropped%29.jpg"}, 
        flag: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Flag_of_Belize.svg/500px-Flag_of_Belize.svg.png"}, 
        symbol: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Coat_of_arms_of_Belize.svg/500px-Coat_of_arms_of_Belize.svg.png"}, 
        map: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/BLZ_orthographic.svg/500px-BLZ_orthographic.svg.png"}, 
        capital: [{"name":"Belmopan","type":"capital"}], 
        largestCity: [{"name":"Belize City","type":"largest city"}], 
        language: {"list":["English"]}, 
        demonym: {"name":"Belizean"}, 
        currency: [{"demonym":"Belize","unit":"dollar"}], 
        tld: {"name":".bz"}, 
    }, 
    {
        country: {"name":"Benin","url":"https://en.wikipedia.org/wiki/Benin"}, 
        leader: {"title":"President","pos":"president","name":"Patrice Talon","url":"https://en.wikipedia.org/wiki/Patrice_Talon","imgUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Patrice_Talon_at_USAID_HQ_%284%29_%28cropped%29.jpg/500px-Patrice_Talon_at_USAID_HQ_%284%29_%28cropped%29.jpg"}, 
        flag: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Flag_of_Benin.svg/500px-Flag_of_Benin.svg.png"}, 
        symbol: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Coat_of_arms_of_Benin.svg/500px-Coat_of_arms_of_Benin.svg.png"}, 
        map: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Benin_%28orthographic_projection_with_inset%29.svg/500px-Benin_%28orthographic_projection_with_inset%29.svg.png"}, 
        capital: [{"name":"Porto-Novo","type":"capital"}], 
        largestCity: [{"name":"Cotonou","type":"largest city"}], 
        language: {"list":["French"]}, 
        demonym: {"name":"Beninese"}, 
        currency: [{"full":"West African CFA franc"}], 
        tld: {"name":".bj"}, 
    }, 
    {
        country: {"name":"Bhutan","url":"https://en.wikipedia.org/wiki/Bhutan"}, 
        leader: {"title":"Prime Minister","pos":"prime minister","name":"Lotay Tshering","url":"https://en.wikipedia.org/wiki/Lotay_Tshering","imgUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Lotay_Tshering_December_2018_crop.jpg/500px-Lotay_Tshering_December_2018_crop.jpg"}, 
        flag: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Flag_of_Bhutan.svg/500px-Flag_of_Bhutan.svg.png"}, 
        symbol: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Emblem_of_Bhutan.svg/500px-Emblem_of_Bhutan.svg.png"}, 
        map: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Bhutan_%28orthographic_projection%29.svg/500px-Bhutan_%28orthographic_projection%29.svg.png"}, 
        capital: [{"name":"Thimphu","type":"capital"}], 
        language: {"list":["Dzongkha"]}, 
        demonym: {"name":"Bhutanese"}, 
        currency: [{"demonym":"Bhutanese","unit":"ngultrum"},{"other":"Indian rupee"}], 
        tld: {"name":".bt"}, 
        largestCity: [{"name":"Thimphu","type":"largest city"}], 
    }, 
    {
        country: {"name":"Bolivia","url":"https://en.wikipedia.org/wiki/Bolivia"}, 
        leader: {"title":"President","pos":"president","name":"Luis Arce","url":"https://en.wikipedia.org/wiki/Luis_Arce","imgUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Luis_Alberto_Arce_Catacora_%28Official_Portrait%2C_2020%29_Cropped_I.png/500px-Luis_Alberto_Arce_Catacora_%28Official_Portrait%2C_2020%29_Cropped_I.png"}, 
        flag: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Flag_of_Bolivia.svg/500px-Flag_of_Bolivia.svg.png"}, 
        symbol: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Banner_of_the_Qulla_Suyu.svg/500px-Banner_of_the_Qulla_Suyu.svg.png"}, 
        map: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/BOL_orthographic.svg/500px-BOL_orthographic.svg.png"}, 
        capital: [{"name":"Sucre","type":"capital"}], 
        largestCity: [{"name":"Santa Cruz","type":"largest city"}], 
        language: {"list":["Spanish","Quechua","Aymara","Guarani"]}, 
        demonym: {"name":"Bolivian"}, 
        currency: [{"demonym":"Bolivian","unit":"boliviano"}], 
        tld: {"name":".bo"}, 
    }, 
    {
        country: {"name":"Bosnia and Herzegovina","url":"https://en.wikipedia.org/wiki/Bosnia_and_Herzegovina"}, 
        leader: {"title":"High Representative","pos":"high representative","name":"Christian Schmidt","url":"https://en.wikipedia.org/wiki/Christian_Schmidt_(politician)","imgUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Christian_Schmidt_%28cropped%29.jpg/500px-Christian_Schmidt_%28cropped%29.jpg"}, 
        flag: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Flag_of_Bosnia_and_Herzegovina.svg/500px-Flag_of_Bosnia_and_Herzegovina.svg.png"}, 
        symbol: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Coat_of_arms_of_Bosnia_and_Herzegovina.svg/500px-Coat_of_arms_of_Bosnia_and_Herzegovina.svg.png"}, 
        map: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Europe-Bosnia_and_Herzegovina.svg/500px-Europe-Bosnia_and_Herzegovina.svg.png"}, 
        capital: [{"name":"Sarajevo","type":"capital"}], 
        language: {"list":["Bosnian","Croatian","Serbian"]}, 
        demonym: {"name":"Bosnian"}, 
        currency: [{"demonym":"Bosnia and Herzegovina","unit":"convertible mark"}], 
        tld: {"name":".ba"}, 
        largestCity: [{"name":"Sarajevo","type":"largest city"}], 
    }, 
    {
        country: {"name":"Botswana","url":"https://en.wikipedia.org/wiki/Botswana"}, 
        leader: {"title":"President","pos":"president","name":"Mokgweetsi Masisi","url":"https://en.wikipedia.org/wiki/Mokgweetsi_Masisi","imgUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Mokgweetsi_E.K._Masisi%2C_President_of_the_Republic_of_Botswana.jpg/500px-Mokgweetsi_E.K._Masisi%2C_President_of_the_Republic_of_Botswana.jpg"}, 
        flag: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_Botswana.svg/500px-Flag_of_Botswana.svg.png"}, 
        symbol: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Coat_of_arms_of_Botswana.svg/500px-Coat_of_arms_of_Botswana.svg.png"}, 
        map: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Botswana_%28centered_orthographic_projection%29.svg/500px-Botswana_%28centered_orthographic_projection%29.svg.png"}, 
        capital: [{"name":"Gaborone","type":"capital"}], 
        language: {"list":["English"]}, 
        demonym: {"name":"Batswana"}, 
        currency: [{"demonym":"Botswana","unit":"pula"}], 
        tld: {"name":".bw"}, 
        largestCity: [{"name":"Gaborone","type":"largest city"}], 
    }, 
    {
        country: {"name":"Brazil","url":"https://en.wikipedia.org/wiki/Brazil"}, 
        leader: {"title":"President","pos":"president","name":"Luiz Inácio Lula da Silva","url":"https://en.wikipedia.org/wiki/Luiz_In%C3%A1cio_Lula_da_Silva","imgUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Foto_oficial_de_Luiz_In%C3%A1cio_Lula_da_Silva_%28estreita%29.jpg/500px-Foto_oficial_de_Luiz_In%C3%A1cio_Lula_da_Silva_%28estreita%29.jpg"}, 
        flag: {"url":"https://upload.wikimedia.org/wikipedia/en/thumb/0/05/Flag_of_Brazil.svg/500px-Flag_of_Brazil.svg.png"}, 
        symbol: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Coat_of_arms_of_Brazil.svg/500px-Coat_of_arms_of_Brazil.svg.png"}, 
        map: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/BRA_orthographic.svg/500px-BRA_orthographic.svg.png"}, 
        capital: [{"name":"Brasília","type":"capital"}], 
        largestCity: [{"name":"São Paulo","type":"largest city"}], 
        language: {"list":["Portuguese"]}, 
        demonym: {"name":"Brazilian"}, 
        currency: [{"demonym":"Brazilian","unit":"real"}], 
        tld: {"name":".br"}, 
    }, 
    {
        country: {"name":"Brunei","url":"https://en.wikipedia.org/wiki/Brunei"}, 
        leader: {"title":"Sultan","pos":"sultan","name":"Hassanal Bolkiah","url":"https://en.wikipedia.org/wiki/Hassanal_Bolkiah","imgUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Hassanal_Bolkiah_at_the_Enthronement_of_Naruhito_%281%29.jpg/500px-Hassanal_Bolkiah_at_the_Enthronement_of_Naruhito_%281%29.jpg"}, 
        flag: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Flag_of_Brunei.svg/500px-Flag_of_Brunei.svg.png"}, 
        symbol: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Emblem_of_Brunei.svg/500px-Emblem_of_Brunei.svg.png"}, 
        map: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Brunei_%28orthographic_projection%29.svg/500px-Brunei_%28orthographic_projection%29.svg.png"}, 
        capital: [{"name":"Bandar Seri Begawan","type":"capital"}], 
        language: {"list":["Malay"]}, 
        demonym: {"name":"Bruneian"}, 
        currency: [{"demonym":"Brunei","unit":"dollar"}], 
        tld: {"name":".bn"}, 
        largestCity: [{"name":"Bandar Seri Begawan","type":"largest city"}], 
    }, 
    {
        country: {"name":"Bulgaria","url":"https://en.wikipedia.org/wiki/Bulgaria"}, 
        leader: {"title":"Prime Minister","pos":"prime minister","name":"Nikolai Denkov","url":"https://en.wikipedia.org/wiki/Nikolai_Denkov","imgUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Nikolai_Denkov_full_portrait_2021.jpg/500px-Nikolai_Denkov_full_portrait_2021.jpg"}, 
        flag: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Bulgaria.svg/500px-Flag_of_Bulgaria.svg.png"}, 
        symbol: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Coat_of_arms_of_Bulgaria.svg/500px-Coat_of_arms_of_Bulgaria.svg.png"}, 
        map: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/EU-Bulgaria.svg/500px-EU-Bulgaria.svg.png"}, 
        capital: [{"name":"Sofia","type":"capital"}], 
        language: {"list":["Bulgarian"]}, 
        demonym: {"name":"Bulgarian"}, 
        currency: [{"demonym":"Bulgarian","unit":"lev"}], 
        tld: {"name":".bg"}, 
        largestCity: [{"name":"Sofia","type":"largest city"}], 
    }, 
    {
        country: {"name":"Burkina Faso","url":"https://en.wikipedia.org/wiki/Burkina_Faso"}, 
        leader: {"title":"President of the Patriotic Movement for Safeguard and Restoration","pos":"president of the Patriotic Movement for Safeguard and Restoration","name":"Ibrahim Traoré","url":"https://en.wikipedia.org/wiki/Ibrahim_Traor%C3%A9","imgUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/thumb/d/d7/Ibrahim_Traor%C3%A9_-_2023_%28cropped%29.png/220px-Ibrahim_Traor%C3%A9_-_2023_%28cropped%29.png/500px-220px-Ibrahim_Traor%C3%A9_-_2023_%28cropped%29.png"}, 
        flag: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Flag_of_Burkina_Faso.svg/500px-Flag_of_Burkina_Faso.svg.png"}, 
        symbol: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Coat_of_arms_of_Burkina_Faso.svg/500px-Coat_of_arms_of_Burkina_Faso.svg.png"}, 
        map: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Burkina_Faso_%28orthographic_projection%29.svg/500px-Burkina_Faso_%28orthographic_projection%29.svg.png"}, 
        capital: [{"name":"Ouagadougou","type":"capital"}], 
        demonym: {}, 
        currency: [{"full":"West African CFA franc"}], 
        tld: {"name":".bf"}, 
        largestCity: [{"name":"Ouagadougou","type":"largest city"}], 
    }, 
    {
        country: {"name":"Burundi","url":"https://en.wikipedia.org/wiki/Burundi"}, 
        leader: {"title":"President","pos":"president","name":"Évariste Ndayishimiye","url":"https://en.wikipedia.org/wiki/%C3%89variste_Ndayishimiye","imgUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/%D0%AD%D0%B2%D0%B0%D1%80%D0%B8%D1%81%D1%82_%D0%9D%D0%B4%D0%B0%D0%B9%D0%B8%D1%88%D0%B8%D0%BC%D0%B8%D0%B5_%2818-02-2022%29_%28cropped%29.jpg/500px-%D0%AD%D0%B2%D0%B0%D1%80%D0%B8%D1%81%D1%82_%D0%9D%D0%B4%D0%B0%D0%B9%D0%B8%D1%88%D0%B8%D0%BC%D0%B8%D0%B5_%2818-02-2022%29_%28cropped%29.jpg"}, 
        flag: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Flag_of_Burundi.svg/500px-Flag_of_Burundi.svg.png"}, 
        symbol: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Coat_of_arms_of_Burundi.svg/500px-Coat_of_arms_of_Burundi.svg.png"}, 
        map: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Burundi_%28orthographic_projection%29.svg/500px-Burundi_%28orthographic_projection%29.svg.png"}, 
        capital: [{"name":"Gitega","type":"capital"}], 
        largestCity: [{"name":"Bujumbura","type":"largest city"}], 
        language: {"list":["Kirundi","French","English"]}, 
        demonym: {}, 
        currency: [{"demonym":"Burundian","unit":"franc"}], 
        tld: {"name":".bi"}, 
    }, 
    {
        country: {"name":"Cambodia","url":"https://en.wikipedia.org/wiki/Cambodia"}, 
        leader: {"title":"President of the People's Party","pos":"president of the People's Party","name":"Hun Sen","url":"https://en.wikipedia.org/wiki/Hun_Sen","imgUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Hun_Sen_July_2019.jpg/500px-Hun_Sen_July_2019.jpg"}, 
        flag: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Flag_of_Cambodia.svg/500px-Flag_of_Cambodia.svg.png"}, 
        symbol: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Royal_arms_of_Cambodia.svg/500px-Royal_arms_of_Cambodia.svg.png"}, 
        map: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Cambodia_on_the_globe_%28Cambodia_centered%29.svg/500px-Cambodia_on_the_globe_%28Cambodia_centered%29.svg.png"}, 
        capital: [{"name":"Phnom Penh","type":"capital"}], 
        language: {"list":["Khmer"]}, 
        demonym: {"name":"Cambodian"}, 
        currency: [{"demonym":"Cambodian","unit":"riel"},{"other":"United States dollar"}], 
        tld: {"name":".kh"}, 
        largestCity: [{"name":"Phnom Penh","type":"largest city"}], 
    }, 
    {
        country: {"name":"Cameroon","url":"https://en.wikipedia.org/wiki/Cameroon"}, 
        leader: {"title":"President","pos":"president","name":"Paul Biya","url":"https://en.wikipedia.org/wiki/Paul_Biya","imgUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Paul_Biya_2014.png/500px-Paul_Biya_2014.png"}, 
        flag: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Flag_of_Cameroon.svg/500px-Flag_of_Cameroon.svg.png"}, 
        symbol: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Coat_of_arms_of_Cameroon.svg/500px-Coat_of_arms_of_Cameroon.svg.png"}, 
        map: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Cameroon_%28orthographic_projection%29.svg/500px-Cameroon_%28orthographic_projection%29.svg.png"}, 
        capital: [{"name":"Yaoundé","type":"capital"}], 
        largestCity: [{"name":"Douala","type":"largest city"}], 
        language: {"list":["French","English"]}, 
        demonym: {"name":"Cameroonian"}, 
        currency: [{"full":"Central African CFA franc"}], 
        tld: {"name":".cm"}, 
    }, 
    {
        country: {"name":"Canada","url":"https://en.wikipedia.org/wiki/Canada"}, 
        leader: {"title":"Prime Minister","pos":"prime minister","name":"Justin Trudeau","url":"https://en.wikipedia.org/wiki/Justin_Trudeau","imgUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Justin_Trudeau_March_2022.jpg/500px-Justin_Trudeau_March_2022.jpg"}, 
        flag: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Canada_%28Pantone%29.svg/500px-Flag_of_Canada_%28Pantone%29.svg.png"}, 
        symbol: {"url":"https://upload.wikimedia.org/wikipedia/en/thumb/4/4f/Coat_of_arms_of_Canada.svg/500px-Coat_of_arms_of_Canada.svg.png"}, 
        map: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/CAN_orthographic.svg/500px-CAN_orthographic.svg.png"}, 
        capital: [{"name":"Ottawa","type":"capital"}], 
        largestCity: [{"name":"Toronto","type":"largest city"}], 
        language: {"list":["English","French"]}, 
        demonym: {"name":"Canadian"}, 
        currency: [{"demonym":"Canadian","unit":"dollar"}], 
        tld: {"name":".ca"}, 
    }, 
    {
        country: {"name":"Cape Verde","url":"https://en.wikipedia.org/wiki/Cape_Verde"}, 
        leader: {"title":"Prime Minister","pos":"prime minister","name":"Ulisses Correia e Silva","url":"https://en.wikipedia.org/wiki/Ulisses_Correia_e_Silva","imgUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Ulisses_Correia_e_Silva.jpg/500px-Ulisses_Correia_e_Silva.jpg"}, 
        flag: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Flag_of_Cape_Verde.svg/500px-Flag_of_Cape_Verde.svg.png"}, 
        symbol: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Coat_of_arms_of_Cape_Verde.svg/500px-Coat_of_arms_of_Cape_Verde.svg.png"}, 
        map: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Cape_Verde_%28orthographic_projection%29.svg/500px-Cape_Verde_%28orthographic_projection%29.svg.png"}, 
        capital: [{"name":"Praia","type":"capital"}], 
        language: {"list":["Portuguese"]}, 
        demonym: {"name":"Cape Verdean"}, 
        currency: [{"demonym":"Cape Verdean","unit":"escudo"}], 
        tld: {"name":".cv"}, 
        largestCity: [{"name":"Praia","type":"largest city"}], 
    }, 
    {
        country: {"name":"the Central African Republic","url":"https://en.wikipedia.org/wiki/Central_African_Republic"}, 
        leader: {"title":"President","pos":"president","name":"Faustin-Archange Touadéra","url":"https://en.wikipedia.org/wiki/Faustin-Archange_Touad%C3%A9ra","imgUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Faustin_Touadera_October_2019.jpg/500px-Faustin_Touadera_October_2019.jpg"}, 
        flag: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Flag_of_the_Central_African_Republic.svg/500px-Flag_of_the_Central_African_Republic.svg.png"}, 
        symbol: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Coat_of_arms_of_the_Central_African_Republic.svg/500px-Coat_of_arms_of_the_Central_African_Republic.svg.png"}, 
        map: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Central_African_Republic_%28centered_orthographic_projection%29.svg/500px-Central_African_Republic_%28centered_orthographic_projection%29.svg.png"}, 
        capital: [{"name":"Bangui","type":"capital"}], 
        language: {"list":["Sango","French"]}, 
        demonym: {"name":"Central African"}, 
        currency: [{"full":"Central African CFA franc"},{"other":"bitcoin"}], 
        tld: {"name":".cf"}, 
        largestCity: [{"name":"Bangui","type":"largest city"}], 
    }, 
    {
        country: {"name":"Chad","url":"https://en.wikipedia.org/wiki/Chad"}, 
        leader: {"title":"Transitional President","pos":"transitional president","name":"Mahamat Déby","url":"https://en.wikipedia.org/wiki/Mahamat_D%C3%A9by","imgUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Mahamat_Idriss_D%C3%A9by_in_2022.jpg/500px-Mahamat_Idriss_D%C3%A9by_in_2022.jpg"}, 
        flag: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Flag_of_Chad.svg/500px-Flag_of_Chad.svg.png"}, 
        symbol: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Coat_of_arms_of_Chad.svg/500px-Coat_of_arms_of_Chad.svg.png"}, 
        map: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Chad_%28orthographic_projection%29.svg/500px-Chad_%28orthographic_projection%29.svg.png"}, 
        capital: [{"name":"N'Djamena","type":"capital"}], 
        language: {"list":["Arabic","French"]}, 
        demonym: {"name":"Chadian"}, 
        currency: [{"full":"Central African CFA franc"}], 
        tld: {"name":".td"}, 
        largestCity: [{"name":"N'Djamena","type":"largest city"}], 
    }, 
    {
        country: {"name":"Chile","url":"https://en.wikipedia.org/wiki/Chile"}, 
        leader: {"title":"President","pos":"president","name":"Gabriel Boric","url":"https://en.wikipedia.org/wiki/Gabriel_Boric","imgUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Retrato_Oficial_Presidente_Boric_Font.jpg/500px-Retrato_Oficial_Presidente_Boric_Font.jpg"}, 
        flag: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Flag_of_Chile.svg/500px-Flag_of_Chile.svg.png"}, 
        symbol: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Coat_of_arms_of_Chile_%28c%29.svg/500px-Coat_of_arms_of_Chile_%28c%29.svg.png"}, 
        map: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/CHL_orthographic_%28%2Ball_claims%29.svg/500px-CHL_orthographic_%28%2Ball_claims%29.svg.png"}, 
        capital: [{"name":"Santiago","type":"capital"}], 
        language: {"list":["Spanish"]}, 
        demonym: {"name":"Chilean"}, 
        currency: [{"demonym":"Chilean","unit":"peso"}], 
        tld: {"name":".cl"}, 
        largestCity: [{"name":"Santiago","type":"largest city"}], 
    }, 
    {
        country: {"name":"China","url":"https://en.wikipedia.org/wiki/China"}, 
        leader: {"title":"General Secretary of the Communist Party","pos":"general secretary of the Communist Party","name":"Xi Jinping","url":"https://en.wikipedia.org/wiki/Xi_Jinping","imgUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Xi_Jinping_with_Macron_and_Von_der_Leyen_2023.jpg/500px-Xi_Jinping_with_Macron_and_Von_der_Leyen_2023.jpg"}, 
        flag: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/500px-Flag_of_the_People%27s_Republic_of_China.svg.png"}, 
        symbol: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/National_Emblem_of_the_People%27s_Republic_of_China_%282%29.svg/500px-National_Emblem_of_the_People%27s_Republic_of_China_%282%29.svg.png"}, 
        map: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/CHN_orthographic.svg/500px-CHN_orthographic.svg.png"}, 
        capital: [{"name":"Beijing","type":"capital"}], 
        largestCity: [{"name":"Shanghai","type":"largest city"}], 
        language: {"list":["Standard Chinese"]}, 
        demonym: {"name":"Chinese"}, 
        currency: [{"full":"renminbi"}], 
        tld: {"name":".cn"}, 
    }, 
    {
        country: {"name":"Colombia","url":"https://en.wikipedia.org/wiki/Colombia"}, 
        leader: {"title":"President","pos":"president","name":"Gustavo Petro","url":"https://en.wikipedia.org/wiki/Gustavo_Petro","imgUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Presidente_Gustavo_Petro_Urrego.jpg/500px-Presidente_Gustavo_Petro_Urrego.jpg"}, 
        flag: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Colombia.svg/500px-Flag_of_Colombia.svg.png"}, 
        symbol: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Coat_of_arms_of_Colombia.svg/500px-Coat_of_arms_of_Colombia.svg.png"}, 
        map: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/COL_orthographic_%28San_Andr%C3%A9s_and_Providencia_special%29.svg/500px-COL_orthographic_%28San_Andr%C3%A9s_and_Providencia_special%29.svg.png"}, 
        capital: [{"name":"Bogotá","type":"capital"}], 
        language: {"list":["Spanish"]}, 
        demonym: {"name":"Colombian"}, 
        currency: [{"demonym":"Colombian","unit":"peso"}], 
        tld: {"name":".co"}, 
        largestCity: [{"name":"Bogotá","type":"largest city"}], 
    }, 
    {
        country: {"name":"the Comoros","url":"https://en.wikipedia.org/wiki/Comoros"}, 
        leader: {"title":"President","pos":"president","name":"Azali Assoumani","url":"https://en.wikipedia.org/wiki/Azali_Assoumani","imgUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Fumio_Kishida_and_Azali_Assoumani_before_the_funeral_of_Shinzo_Abe_%281%29_%28cropped%29.jpg/500px-Fumio_Kishida_and_Azali_Assoumani_before_the_funeral_of_Shinzo_Abe_%281%29_%28cropped%29.jpg"}, 
        flag: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Flag_of_the_Comoros.svg/500px-Flag_of_the_Comoros.svg.png"}, 
        symbol: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Seal_of_the_Comoros.svg/500px-Seal_of_the_Comoros.svg.png"}, 
        map: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Comoros_%28orthographic_projection%29.svg/500px-Comoros_%28orthographic_projection%29.svg.png"}, 
        capital: [{"name":"Moroni","type":"capital"}], 
        language: {"list":["Comorian","French","Arabic"]}, 
        demonym: {"name":"Comorian"}, 
        currency: [{"demonym":"Comorian","unit":"franc"}], 
        tld: {"name":".km"}, 
        largestCity: [{"name":"Moroni","type":"largest city"}], 
    }, 
    {
        country: {"name":"Congo-Kinshasa","url":"https://en.wikipedia.org/wiki/Democratic_Republic_of_the_Congo"}, 
        leader: {"title":"President","pos":"president","name":"Félix Tshisekedi","url":"https://en.wikipedia.org/wiki/F%C3%A9lix_Tshisekedi","imgUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Sergio_Mattarella_F%C3%A9lix_Tshisekedi_al_Quirinale_2021_%282%29_%28cropped%29.jpg/500px-Sergio_Mattarella_F%C3%A9lix_Tshisekedi_al_Quirinale_2021_%282%29_%28cropped%29.jpg"}, 
        flag: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Flag_of_the_Democratic_Republic_of_the_Congo.svg/500px-Flag_of_the_Democratic_Republic_of_the_Congo.svg.png"}, 
        symbol: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Coat_of_Arms_Democratic_Republic_of_Congo.png/500px-Coat_of_Arms_Democratic_Republic_of_Congo.png"}, 
        map: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Democratic_Republic_of_the_Congo_%28orthographic_projection%29.svg/500px-Democratic_Republic_of_the_Congo_%28orthographic_projection%29.svg.png"}, 
        capital: [{"name":"Kinshasa","type":"capital"}], 
        language: {"list":["French"]}, 
        demonym: {"name":"Congolese"}, 
        currency: [{"demonym":"Congolese","unit":"franc"}], 
        tld: {"name":".cd"}, 
        largestCity: [{"name":"Kinshasa","type":"largest city"}], 
    }, 
    {
        country: {"name":"Congo-Brazzaville","url":"https://en.wikipedia.org/wiki/Republic_of_the_Congo"}, 
        leader: {"title":"President","pos":"president","name":"Denis Sassou Nguesso","url":"https://en.wikipedia.org/wiki/Denis_Sassou_Nguesso","imgUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Denis_Sassou_Nguesso_2014.jpg/500px-Denis_Sassou_Nguesso_2014.jpg"}, 
        flag: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Flag_of_the_Republic_of_the_Congo.svg/500px-Flag_of_the_Republic_of_the_Congo.svg.png"}, 
        symbol: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Coat_of_arms_of_the_Republic_of_the_Congo.svg/500px-Coat_of_arms_of_the_Republic_of_the_Congo.svg.png"}, 
        map: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Republic_of_the_Congo_%28orthographic_projection%29.svg/500px-Republic_of_the_Congo_%28orthographic_projection%29.svg.png"}, 
        capital: [{"name":"Brazzaville","type":"capital"}], 
        language: {"list":["French"]}, 
        demonym: {"name":"Congolese"}, 
        currency: [{"full":"Central African CFA franc"}], 
        tld: {"name":".cg"}, 
        largestCity: [{"name":"Brazzaville","type":"largest city"}], 
    }, 
    {
        country: {"name":"Costa Rica","url":"https://en.wikipedia.org/wiki/Costa_Rica"}, 
        leader: {"title":"President","pos":"president","name":"Rodrigo Chaves Robles","url":"https://en.wikipedia.org/wiki/Rodrigo_Chaves_Robles","imgUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Costa_Rican_President_Rodrigo_Chaves_at_the_U.S._Department_of_State_in_Washington%2C_D.C._on_August_30%2C_2023_-_53153106469_%28cropped%29.jpg/500px-Costa_Rican_President_Rodrigo_Chaves_at_the_U.S._Department_of_State_in_Washington%2C_D.C._on_August_30%2C_2023_-_53153106469_%28cropped%29.jpg"}, 
        flag: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Flag_of_Costa_Rica.svg/500px-Flag_of_Costa_Rica.svg.png"}, 
        symbol: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Coat_of_arms_of_Costa_Rica.svg/500px-Coat_of_arms_of_Costa_Rica.svg.png"}, 
        map: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/CRI_orthographic.svg/500px-CRI_orthographic.svg.png"}, 
        capital: [{"name":"San José","type":"capital"}], 
        language: {"list":["Spanish"]}, 
        demonym: {"name":"Costa Rican"}, 
        currency: [{"demonym":"Costa Rican","unit":"colón"}], 
        tld: {"name":".cr"}, 
        largestCity: [{"name":"San José","type":"largest city"}], 
    }, 
    {
        country: {"name":"Croatia","url":"https://en.wikipedia.org/wiki/Croatia"}, 
        leader: {"title":"Prime Minister","pos":"prime minister","name":"Andrej Plenković","url":"https://en.wikipedia.org/wiki/Andrej_Plenkovi%C4%87","imgUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Obisk_predsednika_vlade_Hrva%C5%A1ke_Andreja_Plenkovi%C4%87a_-_28._3._2023_%2852777071695%29_%28cropped%29.jpg/500px-Obisk_predsednika_vlade_Hrva%C5%A1ke_Andreja_Plenkovi%C4%87a_-_28._3._2023_%2852777071695%29_%28cropped%29.jpg"}, 
        flag: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Flag_of_Croatia.svg/500px-Flag_of_Croatia.svg.png"}, 
        symbol: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Coat_of_arms_of_Croatia.svg/500px-Coat_of_arms_of_Croatia.svg.png"}, 
        map: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/EU-Croatia_%28orthographic_projection%29.png/500px-EU-Croatia_%28orthographic_projection%29.png"}, 
        capital: [{"name":"Zagreb","type":"capital"}], 
        language: {"list":["Croatian"]}, 
        demonym: {"name":"Croatian"}, 
        currency: [{"full":"euro"}], 
        tld: {"name":".hr"}, 
        largestCity: [{"name":"Zagreb","type":"largest city"}], 
    }, 
    {
        country: {"name":"Cuba","url":"https://en.wikipedia.org/wiki/Cuba"}, 
        leader: {"title":"First Secretary of the Communist Party","pos":"first secretary of the Communist Party","name":"Miguel Díaz-Canel","url":"https://en.wikipedia.org/wiki/Miguel_D%C3%ADaz-Canel","imgUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Miguel_D%C3%ADaz-Canel_2022-11-22_%28cropped%29.jpg/500px-Miguel_D%C3%ADaz-Canel_2022-11-22_%28cropped%29.jpg"}, 
        flag: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Flag_of_Cuba.svg/500px-Flag_of_Cuba.svg.png"}, 
        symbol: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Coat_of_arms_of_Cuba.svg/500px-Coat_of_arms_of_Cuba.svg.png"}, 
        map: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/CUB_orthographic.svg/500px-CUB_orthographic.svg.png"}, 
        capital: [{"name":"Havana","type":"capital"}], 
        language: {"list":["Spanish"]}, 
        demonym: {"name":"Cuban"}, 
        currency: [{"demonym":"Cuban","unit":"peso"}], 
        tld: {"name":".cu"}, 
        largestCity: [{"name":"Havana","type":"largest city"}], 
    }, 
    {
        country: {"name":"Cyprus","url":"https://en.wikipedia.org/wiki/Cyprus"}, 
        leader: {"title":"President","pos":"president","name":"Nikos Christodoulides","url":"https://en.wikipedia.org/wiki/Nikos_Christodoulides","imgUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/N%C3%ADkos_Christodoul%C3%ADdis%2C_23.03.23.jpg/500px-N%C3%ADkos_Christodoul%C3%ADdis%2C_23.03.23.jpg"}, 
        flag: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Flag_of_Cyprus.svg/500px-Flag_of_Cyprus.svg.png"}, 
        symbol: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Coat_of_arms_of_Cyprus_%282006%29.svg/500px-Coat_of_arms_of_Cyprus_%282006%29.svg.png"}, 
        map: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Republic_of_Cyprus_%28orthographic_projection%29.svg/500px-Republic_of_Cyprus_%28orthographic_projection%29.svg.png"}, 
        capital: [{"name":"Nicosia","type":"capital"}], 
        language: {"list":["Greek","Turkish"]}, 
        demonym: {"name":"Cypriot"}, 
        currency: [{"full":"euro"}], 
        tld: {"name":".cy"}, 
        largestCity: [{"name":"Nicosia","type":"largest city"}], 
    }, 
    {
        country: {"name":"Czechia","url":"https://en.wikipedia.org/wiki/Czech_Republic"}, 
        leader: {"title":"Prime Minister","pos":"prime minister","name":"Petr Fiala","url":"https://en.wikipedia.org/wiki/Petr_Fiala","imgUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Petr_Fiala_%2851940875566%29.jpg/500px-Petr_Fiala_%2851940875566%29.jpg"}, 
        flag: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Flag_of_the_Czech_Republic.svg/500px-Flag_of_the_Czech_Republic.svg.png"}, 
        symbol: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Coat_of_arms_of_the_Czech_Republic.svg/500px-Coat_of_arms_of_the_Czech_Republic.svg.png"}, 
        map: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/EU-Czech_Republic.svg/500px-EU-Czech_Republic.svg.png"}, 
        capital: [{"name":"Prague","type":"capital"}], 
        language: {"list":["Czech"]}, 
        demonym: {"name":"Czech"}, 
        currency: [{"demonym":"Czech","unit":"koruna"}], 
        tld: {"name":".cz"}, 
        largestCity: [{"name":"Prague","type":"largest city"}], 
    }, 
    {
        country: {"name":"Denmark","url":"https://en.wikipedia.org/wiki/Denmark"}, 
        leader: {"title":"Prime Minister","pos":"prime minister","name":"Mette Frederiksen","url":"https://en.wikipedia.org/wiki/Mette_Frederiksen","imgUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Mette_Frederiksen_K%C3%B6%C3%B6penhaminassa_4.5.2022_%2852049397038%29_%28cropped%29.jpg/500px-Mette_Frederiksen_K%C3%B6%C3%B6penhaminassa_4.5.2022_%2852049397038%29_%28cropped%29.jpg"}, 
        flag: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Flag_of_Denmark.svg/500px-Flag_of_Denmark.svg.png"}, 
        symbol: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/National_Coat_of_arms_of_Denmark.svg/500px-National_Coat_of_arms_of_Denmark.svg.png"}, 
        map: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Denmark_%28orthographic_projection%29.svg/500px-Denmark_%28orthographic_projection%29.svg.png"}, 
        capital: [{"name":"Copenhagen","type":"capital"}], 
        language: {"list":["Danish"]}, 
        demonym: {"name":"Danish"}, 
        currency: [{"demonym":"Danish","unit":"krone"}], 
        tld: {"name":".dk"}, 
        largestCity: [{"name":"Copenhagen","type":"largest city"}], 
    }, 
    {
        country: {"name":"Djibouti","url":"https://en.wikipedia.org/wiki/Djibouti"}, 
        leader: {"title":"President","pos":"president","name":"Ismaïl Omar Guelleh","url":"https://en.wikipedia.org/wiki/Isma%C3%AFl_Omar_Guelleh","imgUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Ismail_Omar_Guelleh_2010.jpg/500px-Ismail_Omar_Guelleh_2010.jpg"}, 
        flag: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Flag_of_Djibouti.svg/500px-Flag_of_Djibouti.svg.png"}, 
        symbol: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Emblem_of_Djibouti.svg/500px-Emblem_of_Djibouti.svg.png"}, 
        map: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Djibouti_%28orthographic_projection%29.svg/500px-Djibouti_%28orthographic_projection%29.svg.png"}, 
        capital: [{"name":"Djibouti","type":"capital"}], 
        language: {"list":["Arabic","French"]}, 
        demonym: {"name":"Djiboutian"}, 
        currency: [{"demonym":"Djiboutian","unit":"franc"}], 
        tld: {"name":".dj"}, 
        largestCity: [{"name":"Djibouti","type":"largest city"}], 
    }, 
    {
        country: {"name":"Dominica","url":"https://en.wikipedia.org/wiki/Dominica"}, 
        leader: {"title":"Prime Minister","pos":"prime minister","name":"Roosevelt Skerrit","url":"https://en.wikipedia.org/wiki/Roosevelt_Skerrit","imgUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Swearing_in_of_His_Excellency_Charles_A_Savarin%2C_DAH%2C_President_of_the_Commonwealth_of_Dominica_%2831312241638%29.jpg/500px-Swearing_in_of_His_Excellency_Charles_A_Savarin%2C_DAH%2C_President_of_the_Commonwealth_of_Dominica_%2831312241638%29.jpg"}, 
        flag: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Flag_of_Dominica.svg/500px-Flag_of_Dominica.svg.png"}, 
        symbol: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Coat_of_arms_of_Dominica.svg/500px-Coat_of_arms_of_Dominica.svg.png"}, 
        map: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Dominica_on_the_globe_%28Americas_centered%29.svg/500px-Dominica_on_the_globe_%28Americas_centered%29.svg.png"}, 
        capital: [{"name":"Roseau","type":"capital"}], 
        language: {"list":["English"]}, 
        demonym: {"name":"Dominican"}, 
        currency: [{"full":"East Caribbean dollar"}], 
        tld: {"name":".dm"}, 
        largestCity: [{"name":"Roseau","type":"largest city"}], 
    }, 
    {
        country: {"name":"the Dominican Republic","url":"https://en.wikipedia.org/wiki/Dominican_Republic"}, 
        leader: {"title":"President","pos":"president","name":"Luis Abinader","url":"https://en.wikipedia.org/wiki/Luis_Abinader","imgUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Luis_Abinader_en_2022.jpg/500px-Luis_Abinader_en_2022.jpg"}, 
        flag: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_the_Dominican_Republic.svg/500px-Flag_of_the_Dominican_Republic.svg.png"}, 
        symbol: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Coat_of_arms_of_the_Dominican_Republic.svg/500px-Coat_of_arms_of_the_Dominican_Republic.svg.png"}, 
        map: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Dominican_Republic_%28orthographic_projection%29.svg/500px-Dominican_Republic_%28orthographic_projection%29.svg.png"}, 
        capital: [{"name":"Santo Domingo","type":"capital"}], 
        language: {"list":["Spanish"]}, 
        demonym: {"name":"Dominican"}, 
        currency: [{"demonym":"Dominican","unit":"peso"}], 
        tld: {"name":".do"}, 
        largestCity: [{"name":"Santo Domingo","type":"largest city"}], 
    }, 
    {
        country: {"name":"East Timor","url":"https://en.wikipedia.org/wiki/East_Timor"}, 
        leader: {"title":"Prime Minister","pos":"prime minister","name":"Xanana Gusmão","url":"https://en.wikipedia.org/wiki/Xanana_Gusm%C3%A3o","imgUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Xanana_2011_%28cropped%29.jpg/500px-Xanana_2011_%28cropped%29.jpg"}, 
        flag: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Flag_of_East_Timor.svg/500px-Flag_of_East_Timor.svg.png"}, 
        symbol: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Coat_of_arms_of_East_Timor.svg/500px-Coat_of_arms_of_East_Timor.svg.png"}, 
        map: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Timor_Leste_%28orthographic_projection%29.svg/500px-Timor_Leste_%28orthographic_projection%29.svg.png"}, 
        capital: [{"name":"Dili","type":"capital"}], 
        language: {"list":["Portuguese","Tetum"]}, 
        demonym: {"name":"East Timorese"}, 
        currency: [{"full":"United States dollar"}], 
        tld: {"name":".tl"}, 
        largestCity: [{"name":"Dili","type":"largest city"}], 
    }, 
    {
        country: {"name":"Ecuador","url":"https://en.wikipedia.org/wiki/Ecuador"}, 
        leader: {"title":"President","pos":"president","name":"Guillermo Lasso","url":"https://en.wikipedia.org/wiki/Guillermo_Lasso","imgUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Guillermo_Lasso_2023.jpg/500px-Guillermo_Lasso_2023.jpg"}, 
        flag: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Flag_of_Ecuador.svg/500px-Flag_of_Ecuador.svg.png"}, 
        symbol: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Coat_of_arms_of_Ecuador.svg/500px-Coat_of_arms_of_Ecuador.svg.png"}, 
        map: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/ECU_orthographic.svg/500px-ECU_orthographic.svg.png"}, 
        capital: [{"name":"Quito","type":"capital"}], 
        language: {"list":["Spanish"]}, 
        demonym: {"name":"Ecuadorian"}, 
        currency: [{"full":"United States dollar"}], 
        tld: {"name":".ec"}, 
        largestCity: [{"name":"Quito","type":"largest city"}], 
    }, 
    {
        country: {"name":"Egypt","url":"https://en.wikipedia.org/wiki/Egypt"}, 
        leader: {"title":"President","pos":"president","name":"Abdel Fattah el-Sisi","url":"https://en.wikipedia.org/wiki/Abdel_Fattah_el-Sisi","imgUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/AbdelFattah_Elsisi_%28cropped%29.jpg/500px-AbdelFattah_Elsisi_%28cropped%29.jpg"}, 
        flag: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_Egypt.svg/500px-Flag_of_Egypt.svg.png"}, 
        symbol: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Coat_of_arms_of_Egypt_%28Official%29.svg/500px-Coat_of_arms_of_Egypt_%28Official%29.svg.png"}, 
        map: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/EGY_orthographic.svg/500px-EGY_orthographic.svg.png"}, 
        capital: [{"name":"Cairo","type":"capital"}], 
        language: {"list":["Arabic"]}, 
        demonym: {"name":"Egyptian"}, 
        currency: [{"demonym":"Egyptian","unit":"pound"}], 
        tld: {"name":".eg"}, 
        largestCity: [{"name":"Cairo","type":"largest city"}], 
    }, 
    {
        country: {"name":"El Salvador","url":"https://en.wikipedia.org/wiki/El_Salvador"}, 
        leader: {"title":"President","pos":"president","name":"Nayib Bukele","url":"https://en.wikipedia.org/wiki/Nayib_Bukele","imgUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Presidente_Nayib_Bukele_%28cropped%29.jpg/500px-Presidente_Nayib_Bukele_%28cropped%29.jpg"}, 
        flag: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Flag_of_El_Salvador.svg/500px-Flag_of_El_Salvador.svg.png"}, 
        symbol: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Coat_of_arms_of_El_Salvador.svg/500px-Coat_of_arms_of_El_Salvador.svg.png"}, 
        map: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/El_Salvador_%28orthographic_projection%29.svg/500px-El_Salvador_%28orthographic_projection%29.svg.png"}, 
        capital: [{"name":"San Salvador","type":"capital"}], 
        language: {"list":["Spanish"]}, 
        demonym: {"name":"Salvadoran"}, 
        currency: [{"full":"United States dollar"},{"other":"bitcoin"}], 
        tld: {"name":".sv"}, 
        largestCity: [{"name":"San Salvador","type":"largest city"}], 
    }, 
    {
        country: {"name":"Equatorial Guinea","url":"https://en.wikipedia.org/wiki/Equatorial_Guinea"}, 
        leader: {"title":"President","pos":"president","name":"Teodoro Obiang Nguema Mbasogo","url":"https://en.wikipedia.org/wiki/Teodoro_Obiang_Nguema_Mbasogo","imgUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Teodoro_Obiang_2019_%28cropped%29.jpg/500px-Teodoro_Obiang_2019_%28cropped%29.jpg"}, 
        flag: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Flag_of_Equatorial_Guinea.svg/500px-Flag_of_Equatorial_Guinea.svg.png"}, 
        symbol: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Coat_of_arms_of_Equatorial_Guinea.svg/500px-Coat_of_arms_of_Equatorial_Guinea.svg.png"}, 
        map: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/GNQ_orthographic.svg/500px-GNQ_orthographic.svg.png"}, 
        capital: [{"name":"Malabo","type":"capital"}], 
        largestCity: [{"name":"Malabo","type":"largest city"}], 
        language: {"list":["Spanish","French","Portuguese"]}, 
        demonym: {"name":"Equatoguinean"}, 
        currency: [{"full":"Central African CFA franc"}], 
        tld: {"name":".gq"}, 
    }, 
    {
        country: {"name":"Eritrea","url":"https://en.wikipedia.org/wiki/Eritrea"}, 
        leader: {"title":"President","pos":"president","name":"Isaias Afwerki","url":"https://en.wikipedia.org/wiki/Isaias_Afwerki","imgUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Isaias_Afwerki_%282023-05-31%29.jpg/500px-Isaias_Afwerki_%282023-05-31%29.jpg"}, 
        flag: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Flag_of_Eritrea.svg/500px-Flag_of_Eritrea.svg.png"}, 
        symbol: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Emblem_of_Eritrea_%28or_argent_azur%29.svg/500px-Emblem_of_Eritrea_%28or_argent_azur%29.svg.png"}, 
        map: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Eritrea_%28Africa_orthographic_projection%29.svg/500px-Eritrea_%28Africa_orthographic_projection%29.svg.png"}, 
        capital: [{"name":"Asmara","type":"capital"}], 
        language: {"list":["Tigrinya","Arabic","English",null]}, 
        demonym: {"name":"Eritrean"}, 
        currency: [{"demonym":"Eritrean","unit":"nakfa"}], 
        tld: {"name":".er"}, 
        largestCity: [{"name":"Asmara","type":"largest city"}], 
    }, 
    {
        country: {"name":"Estonia","url":"https://en.wikipedia.org/wiki/Estonia"}, 
        leader: {"title":"Prime Minister","pos":"prime minister","name":"Kaja Kallas","url":"https://en.wikipedia.org/wiki/Kaja_Kallas","imgUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Kaja_Kallas_%28crop%29.jpg/500px-Kaja_Kallas_%28crop%29.jpg"}, 
        flag: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Coat_of_arms_of_Estonia.svg/500px-Coat_of_arms_of_Estonia.svg.png"}, 
        symbol: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/EU-Estonia.svg/500px-EU-Estonia.svg.png"}, 
        map: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Increase_Neutral.svg/500px-Increase_Neutral.svg.png"}, 
        capital: [{"name":"Tallinn","type":"capital"}], 
        language: {"list":["Estonian"]}, 
        demonym: {"name":"Estonian"}, 
        currency: [{"full":"euro"}], 
        tld: {"name":".ee"}, 
        largestCity: [{"name":"Tallinn","type":"largest city"}], 
    }, 
    {
        country: {"name":"Eswatini","url":"https://en.wikipedia.org/wiki/Eswatini"}, 
        leader: {"title":"Ngwenyama","pos":"ngwenyama","name":"Mswati III","url":"https://en.wikipedia.org/wiki/Mswati_III","imgUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/King_Mswati_III_2014.jpg/500px-King_Mswati_III_2014.jpg"}, 
        flag: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Flag_of_Eswatini.svg/500px-Flag_of_Eswatini.svg.png"}, 
        symbol: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Coat_of_arms_of_Eswatini.svg/500px-Coat_of_arms_of_Eswatini.svg.png"}, 
        map: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Eswatini_on_the_globe_%28special_marker%29_%28Madagascar_centered%29.svg/500px-Eswatini_on_the_globe_%28special_marker%29_%28Madagascar_centered%29.svg.png"}, 
        capital: [], 
        largestCity: [{"name":"Mbabane","type":"largest city"}], 
        language: {"list":["Swazi","English"]}, 
        demonym: {"name":"Swazi"}, 
        currency: [{"demonym":"Swazi","unit":"lilangeni"},{"other":"South African rand"}], 
        tld: {"name":".sz"}, 
    }, 
    {
        country: {"name":"Ethiopia","url":"https://en.wikipedia.org/wiki/Ethiopia"}, 
        leader: {"title":"Prime Minister","pos":"prime minister","name":"Abiy Ahmed","url":"https://en.wikipedia.org/wiki/Abiy_Ahmed","imgUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Abiy_Ahmed_with_LI_Yong_2018_%28cropped%29.jpeg/500px-Abiy_Ahmed_with_LI_Yong_2018_%28cropped%29.jpeg"}, 
        flag: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Flag_of_Ethiopia.svg/500px-Flag_of_Ethiopia.svg.png"}, 
        symbol: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Emblem_of_Ethiopia.svg/500px-Emblem_of_Ethiopia.svg.png"}, 
        map: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Ethiopia_%28Africa_orthographic_projection%29.svg/500px-Ethiopia_%28Africa_orthographic_projection%29.svg.png"}, 
        capital: [{"name":"Addis Ababa","type":"capital"}], 
        language: {"list":["Afar"]}, 
        demonym: {"name":"Ethiopian"}, 
        currency: [{"demonym":"Ethiopian","unit":"birr"}], 
        tld: {"name":".et"}, 
        largestCity: [{"name":"Addis Ababa","type":"largest city"}], 
    }, 
    {
        country: {"name":"Fiji","url":"https://en.wikipedia.org/wiki/Fiji"}, 
        leader: {"title":"Prime Minister","pos":"prime minister","name":"Sitiveni Rabuka","url":"https://en.wikipedia.org/wiki/Sitiveni_Rabuka","imgUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Sitiveni_Rabuka_2020.jpg/500px-Sitiveni_Rabuka_2020.jpg"}, 
        flag: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Flag_of_Fiji.svg/500px-Flag_of_Fiji.svg.png"}, 
        symbol: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Coat_of_arms_of_Fiji.svg/500px-Coat_of_arms_of_Fiji.svg.png"}, 
        map: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Fiji_on_the_globe_%28small_islands_magnified%29_%28Polynesia_centered%29.svg/500px-Fiji_on_the_globe_%28small_islands_magnified%29_%28Polynesia_centered%29.svg.png"}, 
        capital: [{"name":"Suva","type":"capital"}], 
        language: {"list":["English","iTaukei","Hindi"]}, 
        demonym: {"name":"Fijian"}, 
        currency: [{"demonym":"Fijian","unit":"dollar"}], 
        tld: {"name":".fj"}, 
        largestCity: [{"name":"Suva","type":"largest city"}], 
    }, 
    {
        country: {"name":"Finland","url":"https://en.wikipedia.org/wiki/Finland"}, 
        leader: {"title":"Prime Minister","pos":"prime minister","name":"Petteri Orpo","url":"https://en.wikipedia.org/wiki/Petteri_Orpo","imgUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Petteri-Orpo-01_%28cropped%29.jpg/500px-Petteri-Orpo-01_%28cropped%29.jpg"}, 
        flag: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Finland.svg/500px-Flag_of_Finland.svg.png"}, 
        symbol: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Coat_of_arms_of_Finland_2.svg/500px-Coat_of_arms_of_Finland_2.svg.png"}, 
        map: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/EU-Finland_%28orthographic_projection%29.svg/500px-EU-Finland_%28orthographic_projection%29.svg.png"}, 
        capital: [{"name":"Helsinki","type":"capital"}], 
        language: {"list":["Finnish","Swedish"]}, 
        demonym: {"name":"Finnish"}, 
        currency: [{"full":"euro"}], 
        tld: {"name":".fi"}, 
        largestCity: [{"name":"Helsinki","type":"largest city"}], 
    }, 
    {
        country: {"name":"France","url":"https://en.wikipedia.org/wiki/France"}, 
        leader: {"title":"President","pos":"president","name":"Emmanuel Macron","url":"https://en.wikipedia.org/wiki/Emmanuel_Macron","imgUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Emmanuel_Macron_2023_%28cropped%29.jpg/500px-Emmanuel_Macron_2023_%28cropped%29.jpg"}, 
        flag: {"url":"https://upload.wikimedia.org/wikipedia/en/thumb/c/c3/Flag_of_France.svg/500px-Flag_of_France.svg.png"}, 
        symbol: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Armoiries_r%C3%A9publique_fran%C3%A7aise.svg/500px-Armoiries_r%C3%A9publique_fran%C3%A7aise.svg.png"}, 
        map: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/EU-France_%28orthographic_projection%29.svg/500px-EU-France_%28orthographic_projection%29.svg.png"}, 
        capital: [{"name":"Paris","type":"capital"}], 
        language: {"list":["French"]}, 
        demonym: {"name":"French"}, 
        currency: [{"full":"euro"}], 
        tld: {"name":".fr"}, 
        largestCity: [{"name":"Paris","type":"largest city"}], 
    }, 
    {
        country: {"name":"Gabon","url":"https://en.wikipedia.org/wiki/Gabon"}, 
        leader: {"title":"Chairman of the Committee for the Transition and Restoration of Institutions","pos":"chairman of the Committee for the Transition and Restoration of Institutions","name":"Brice Clotaire Oligui Nguema","url":"https://en.wikipedia.org/wiki/Brice_Clotaire_Oligui_Nguema","imgUrl":"https://up500px-Ambox_current_red.svg.png"}, 
        flag: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Flag_of_Gabon.svg/500px-Flag_of_Gabon.svg.png"}, 
        symbol: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Coat_of_arms_of_Gabon.svg/500px-Coat_of_arms_of_Gabon.svg.png"}, 
        map: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Gabon_%28orthographic_projection%29.svg/500px-Gabon_%28orthographic_projection%29.svg.png"}, 
        capital: [{"name":"Libreville","type":"capital"}], 
        language: {"list":["French"]}, 
        demonym: {"name":"Gabonese"}, 
        currency: [{"full":"Central African CFA franc"}], 
        tld: {"name":".ga"}, 
        largestCity: [{"name":"Libreville","type":"largest city"}], 
    }, 
    {
        country: {"name":"The Gambia","url":"https://en.wikipedia.org/wiki/The_Gambia"}, 
        leader: {"title":"President","pos":"president","name":"Adama Barrow","url":"https://en.wikipedia.org/wiki/Adama_Barrow","imgUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/Adama_Barrow_-_2018_%2839774084330%29_%28cropped%29.jpg/500px-Adama_Barrow_-_2018_%2839774084330%29_%28cropped%29.jpg"}, 
        flag: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Flag_of_The_Gambia.svg/500px-Flag_of_The_Gambia.svg.png"}, 
        symbol: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Coat_of_arms_of_The_Gambia.svg/500px-Coat_of_arms_of_The_Gambia.svg.png"}, 
        map: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Gambia_%28orthographic_projection_with_inset%29.svg/500px-Gambia_%28orthographic_projection_with_inset%29.svg.png"}, 
        capital: [{"name":"Banjul","type":"capital"}], 
        largestCity: [{"name":"Serekunda","type":"largest metropolitan area"}], 
        language: {"list":["English"]}, 
        demonym: {"name":"Gambian"}, 
        currency: [{"demonym":"Gambian","unit":"dalasi"}], 
        tld: {"name":".gm"}, 
    }, 
    {
        country: {"name":"Georgia","url":"https://en.wikipedia.org/wiki/Georgia_(country)"}, 
        leader: {"title":"Prime Minister","pos":"prime minister","name":"Irakli Garibashvili","url":"https://en.wikipedia.org/wiki/Irakli_Garibashvili","imgUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/PM_Garibashvili%2C_Munich_Security_Conference%2C_Munich_-_Hotel_Bayerischer_Hof.jpg/500px-PM_Garibashvili%2C_Munich_Security_Conference%2C_Munich_-_Hotel_Bayerischer_Hof.jpg"}, 
        flag: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Flag_of_Georgia.svg/500px-Flag_of_Georgia.svg.png"}, 
        symbol: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Greater_coat_of_arms_of_Georgia.svg/500px-Greater_coat_of_arms_of_Georgia.svg.png"}, 
        map: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Georgia_%28orthographic_projection_with_inset%29.svg/500px-Georgia_%28orthographic_projection_with_inset%29.svg.png"}, 
        capital: [{"name":"Tbilisi","type":"capital"}], 
        language: {"list":["Georgian"]}, 
        demonym: {"name":"Georgian"}, 
        currency: [{"demonym":"Georgian","unit":"lari"}], 
        tld: {"name":".ge"}, 
        largestCity: [{"name":"Tbilisi","type":"largest city"}], 
    }, 
    {
        country: {"name":"Germany","url":"https://en.wikipedia.org/wiki/Germany"}, 
        leader: {"title":"Chancellor","pos":"chancellor","name":"Olaf Scholz","url":"https://en.wikipedia.org/wiki/Olaf_Scholz","imgUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Olaf_Scholz_in_2023_%28cropped%29.jpg/500px-Olaf_Scholz_in_2023_%28cropped%29.jpg"}, 
        flag: {"url":"https://upload.wikimedia.org/wikipedia/en/thumb/b/ba/Flag_of_Germany.svg/500px-Flag_of_Germany.svg.png"}, 
        symbol: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Coat_of_arms_of_Germany.svg/500px-Coat_of_arms_of_Germany.svg.png"}, 
        map: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/EU-Germany_%28orthographic_projection%29.svg/500px-EU-Germany_%28orthographic_projection%29.svg.png"}, 
        capital: [{"name":"Berlin","type":"capital"}], 
        language: {"list":["German"]}, 
        demonym: {"name":"German"}, 
        currency: [{"full":"euro"}], 
        tld: {"name":".de"}, 
        largestCity: [{"name":"Berlin","type":"largest city"}], 
    }, 
    {
        country: {"name":"Ghana","url":"https://en.wikipedia.org/wiki/Ghana"}, 
        leader: {"title":"President","pos":"president","name":"Nana Akufo-Addo","url":"https://en.wikipedia.org/wiki/Nana_Akufo-Addo","imgUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Nana_Akufo_Addo%2C_Jan._2020.jpg/500px-Nana_Akufo_Addo%2C_Jan._2020.jpg"}, 
        flag: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Flag_of_Ghana.svg/500px-Flag_of_Ghana.svg.png"}, 
        symbol: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Coat_of_arms_of_Ghana.svg/500px-Coat_of_arms_of_Ghana.svg.png"}, 
        map: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Ghana_%28orthographic_projection%29.svg/500px-Ghana_%28orthographic_projection%29.svg.png"}, 
        capital: [{"name":"Accra","type":"capital"}], 
        language: {"list":["English"]}, 
        demonym: {"name":"Ghanaian"}, 
        currency: [{"demonym":"Ghanaian","unit":"cedi"}], 
        tld: {"name":".gh"}, 
        largestCity: [{"name":"Accra","type":"largest city"}], 
    }, 
    {
        country: {"name":"Greece","url":"https://en.wikipedia.org/wiki/Greece"}, 
        leader: {"title":"Prime Minister","pos":"prime minister","name":"Kyriakos Mitsotakis","url":"https://en.wikipedia.org/wiki/Kyriakos_Mitsotakis","imgUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Kyriakos_Mitsotakis_%282021-12-08%29_03_%28cropped%29.jpg/500px-Kyriakos_Mitsotakis_%282021-12-08%29_03_%28cropped%29.jpg"}, 
        flag: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_Greece.svg/500px-Flag_of_Greece.svg.png"}, 
        symbol: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Coat_of_arms_of_Greece.svg/500px-Coat_of_arms_of_Greece.svg.png"}, 
        map: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/EU-Greece_%28orthographic_projection%29.svg/500px-EU-Greece_%28orthographic_projection%29.svg.png"}, 
        capital: [{"name":"Athens","type":"capital"}], 
        language: {"list":["Greek"]}, 
        demonym: {"name":"Greek"}, 
        currency: [{"full":"euro"}], 
        tld: {"name":".gr"}, 
        largestCity: [{"name":"Athens","type":"largest city"}], 
    }, 
    {
        country: {"name":"Grenada","url":"https://en.wikipedia.org/wiki/Grenada"}, 
        leader: {"title":"Prime Minister","pos":"prime minister","name":"Dickon Mitchell","url":"https://en.wikipedia.org/wiki/Dickon_Mitchell","imgUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Dickon_Mitchell_2022-07-01.jpg/500px-Dickon_Mitchell_2022-07-01.jpg"}, 
        flag: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Grenada.svg/500px-Flag_of_Grenada.svg.png"}, 
        symbol: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Coat_of_arms_of_Grenada.svg/500px-Coat_of_arms_of_Grenada.svg.png"}, 
        map: {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Grenada_on_the_globe_%28Americas_centered%29.svg/500px-Grenada_on_the_globe_%28Americas_centered%29.svg.png"}, 
        capital: [{"name":"St. George's","type":"capital"}], 
        language: {"list":["English"]}, 
        demonym: {"name":"Grenadian"}, 
        currency: [{"full":"East Caribbean dollar"}], 
        tld: {"name":".gd"}, 
        largestCity: [{"name":"St. George's","type":"largest city"}], 
    }, 
];
module.exports = { newInfo }